#pragma once

#define YTD_APP_VERSION_MAJOR 1
#define YTD_APP_VERSION_MINOR 2
#define YTD_APP_VERSION_PATCH 0
#define YTD_APP_VERSION_BUILD 0

#define YTD_APP_VERSION_STRING "1.2.0"
#define YTD_APP_VERSION_WIDE L"1.2.0"
#define YTD_APP_FILE_VERSION_STRING "1.2.0.0"
#define YTD_APP_FILE_VERSION_RC 1,2,0,0
